spring:
  mvc:
    view:
      suffix: .html
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

cloud:
  aws:
    s3:
      bucket: repsac
    region:
      static: us-east-1
      auto: false
    stack:
      auto: false
    credentials:
      access-key: <access-key>
      secret-key: <secret-key>
#AWS 환경이 아닐때 에러 해결
logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error
